#!/bin/bash

#!/bin/bash
# read three numbers and assigned them to 3 vars
read -p "Enter number one : " n1
read -p "Enter number two : " n2
read -p "Enter number three : " n3
: <<'END'
if [ $n1 -gt $n2 ] && [ $n1 -gt $n3 ]
then
echo "$n1 ir lielakais skaitlis"
elif [ $n2 -gt $n1 ] && [ $n2 -gt $n3 ]
then
echo "$n2 ir lielakais skaitlis"
elif [ $n3 -gt $n1 ] && [ $n3 -gt $n2 ]
then
echo "$n3 ir lielakais skaitlis"
fi
END

#vid=$(((n1+n2+n3)/3))
#vid2=$((((n1+n2+n3)%3*10)/3))
#echo  "( $n1 + $n2 + $n3) / 3 = $vid" 
#echo "(( $n1 + $n2 + $n3 ) % 3 *10 ) / 3) = $vid2"
#echo "$vid . $vid2 ir videjais aritmetiskais"

#echo -e "$n1\n$n2\n$n3" | sort -n

if [ $n1 -gt $n2 ] && [ $n1 -gt $n3 ] && [ $n2 -gt $n3 ]
then
echo -e "$n1\n$n2\n$n3"
elif [ $n1 -gt $n2 ] && [ $n1 -gt $n3 ] && [ $n3 -gt $n2]
then
echo -e "$n1\n$n3\n$n2"
elif [ $n2 -gt $n1 ] && [ $n2 -gt $n3 ] && [ $n1 -gt $n3 ]
then
echo -e "$n2\n$n1\n$n3"
elif [ $n2 -gt $n1 ] && [ $n2 -gt $n3 ] && [ $n3 -gt $n1 ]
then
echo -e "$n2\n$n3\n$n1"
elif [ $n3 -gt $n2 ] && [ $n3 -gt $n1 ] && [ $n1 -gt $n2 ]
then
echo -e "$n3\n$n1\n$n2"
elif [ $n3 -gt $n2 ] && [ $n3 -gt $n1 ] && [ $n2 -gt $n1 ]
then
echo -e "$n3\n$n2\n$n1" 
fi
